#+TITLE: The Great Rebalancing, by Michael Pettis
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/new.css" />
#+AUTHOR: Siva Swaminathan
#+DATE: June 2020
#+OPTIONS: toc:nil

(2013), so it is interesting to see how the book has aged.

- The way I would phrase his punchline: *In a globalized world, all domestic policy is trade policy.*
- Makes the point (and cites consensus among economic historians) that imperialism was driven by finding a market for excess production ("savings") generated by the industrial revolution (Ref: Hobson, Luxemburg, Lenin)
- $\textrm{GDP} \equiv \textrm{Consumption} + \textrm{Surplus (invested productively or not)}$ (eg: Refers to production surplus as "savings" which is unusual; normal English usage would lead one to consider /uninvested & fungible/ capital as savings, not quite production in excess of consumption, but maybe the wording is not crucial for the argument)(Seems like "GDP = Consumption + Savings/Investment" by definition, so any unconsumed surplus is called "savings")
- In summary, the only time it makes sense for a country to suppress wages (i.e. household income, which will mostly go towards consumption) is when it has high unemployment. In that case, increased investment compared to consumption will promote productive investment (/especially towards export/), and hence increase employment. After reaching high employment, continuing to suppress household income is effectively forcing unemployment in countries with policies less oriented towards thrift.
- Financial repression through low interest rates might effectively be similar to devaluing the currency, because it shifts resources from households (consumption) to businesses (investment).

* On production surpluses and income inequality (appendix)
- Age of mass production & mass consumption. Lacking capital for mass consumption, non-savers reduce consumption, so there's no return for savers investing capital to boost production -- unless consumers take on debt. So, /rising income inequality forces up the savings rate/ since rich people can't/don't consume proportional to wealth (or redistribute for others to consume). If credit cannot surge enough, another consequence is rising unemployment (decreased production to match decreased demand) (This is what triggered New Deal policy making, as a response to Gilded Age inequality -- Marriner Eccles FRB Chairman 1932-1948).
- If household income (as a fraction of GDP) shrinks, then households retain (and therefore consume) a smaller fraction of their productivity.
- Pettis argues that different policies in Germany & China which transfer money from households (suppress consumption) to producers (boost production) have similar effects.
  - In Germany, agreement circa ~2000 to restrain wage growth lower than productivity. German euro is "undervalued" in relation to Spain, Italy, France having "overvalued" euro.
  - In China, caused by a combination of large (rural) unemployment rate (and export-focused policies?). Undervalued yuan since 1994, and artificially low interest rates.
- If there are available avenues for productive investment (i.e. capital is the limiting factor determining growth i.e. "capital-ism"), inequality is a good eay of financing them -- since the rich will likely invest marginal gains, compared to the poor who will likely consume marginal gains. (Many developing countries suffer because of insufficient savings to bootstrap productive investments, simultaneously creating jobs).
- Productivity improvements could result in increasing incomes or inequality (empirical analysis: Piketty's r-vs-g). When productivity improvements are sufficiently high (the target of juicy investment opportunities i.e. low-hanging fruit), household quality-of-life increases even when inequality does (can now consume more per unit income, so okay if incomes don't grow as much, esp. as a fraction of GDP), and the increased inequality is used to sponsor the next round of productivity improvements. This is the crux of the "trickle down" theory (where capitalists are mythologized as "job creators" leading progress; the phase the US "elite" believe themselves to be in).
** What happens when savings rise (due to increasing income inequality)?
As an immediate consequence, productive investment must rise with savings, or it can be siphoned off into wasteful investment (excess inventory, or other useless endeavors).
- But (as Eccles pointed out) since the purpose of investment today is (to profit off) increased consumption tomorrow, productive investment will only happen if inequality were not permanent (and about to reverse). So, unlikely to get increase in productive investment.
- Over short time periods, increasing inequality can be "buffered" by increasing inventory -- but likely people will not stupidly continue that over long periods.
- Too much capital, and not enough investing opportunities, so interest rates will naturally fall -- and suddenly cheap capital will likely lead to speculative asset bubbles! Example unproductive investments:
  - Infrastructure: unused {lavish buildings, swanky airports, highways, hosting a mega sporting event, etc}. Pettis claims: Arizona housing tracts, Dublin apartments, Spanish airports, Chinese ghost cities, etc.
  - Financial assets: overvalued securities.
  - Investment in zero-sum games (eg: Softbank -- WeWork and Uber; What about SuperPACs -- too small in scale?)
** Can savings increase be somehow avoided, even under increasing inequality?
Needs transfer of wealth from the rich to the poor. (eg: redistributive taxation to fuel consumption)
  1. Wealthy households "consume" proportionally to income. Generically unlikely to happen, but one set of possibilities eg: by funding charity, research(alternatively seen as productive investment), etc (eg: Gilded age; Bill Gates). Also, politically unsustainable in a democracy.
  2. Lower savings from poorer people to offset increased savings from wealthy people. eg: debt-fueled consumption (eg: student, home, credit-card loans; health-care funding?) but this is only possible whe there is an asset bubble (borrow against assets with increasing value, eg: houses, college degrees, etc.)
     - Note: An (eventual) debt jubilee is akin to redistributive taxation, except morally unfair in punishing poor savers who held off unwise consumption (hence politicallly untenable, unless done "uniformly" eg: universal college education)
  3. Increasing unemployment, so that you have a segment of population whose income drops to zero but consumption cannot, so they contribute negative to savings (either dip into their own savings, or borrow from others savings, or welfare from govt., or crime, etc.). This also reduces GDP, thereby reducing savings (since basic consumption will remain constant)
** Universal thrift, and the tragedy of the commons
- Bernard Mandeville's /Fable of the bees/ was considered "un-christian" for stating that spending by the rich was good for the poor, and everyone becoming thrifty would be a disaster! (Interesting relation to Max Weber's Protestant ethic and the spirit of capitalism)
- John Hobson, Confessions of an economic heretic (~1930s)
- Thrift is great at an individual level; why not at the universal level?
  - Thrift is either productive investment, or optionality by deferring consumption. If nobody is doing enough consumption today, the cycle breaks and economic flywheel decelerates. If everyone held on to money for optionality, no-one would be doing any value-generating activity. Yet another tragedy of the commons! (let others spend today, and I shall spend tomorrow when I might get more bang for the my buck, compared to today!)
** Applying these ideas to what we observe in the world
- Summary table of possible equilibrating responses to increased savings from income inequality.
  - Of the six options, only "sustainable"[fn:: nature has a way of /forcing/ ecosystems to become sustainable] ones are to put savings towards productive investments, or unemployment (or welfare -- either by the rich, or through the government with VERY HIGH marginal tax rates, which is one of the sub-cases of "linear consumption").
  - In the current political climate (welfare unlikely), if productive investments don't absorb savings, the only macroeconomic solution is unemployment.
- In the intermediate term, unsustainable possibilities include debt-fueled consumption, but that will likely increase debt beyond serviceable levels, so unlikely to continue.
  - Examples galore in the US
  - Credit-financed consumption in Southern Europe, Housing bubbles around the (China, Canada, India?).
- Historically, unemployment starts in regions with fastest increase in debt (eg: US), but soon direct/indirect interventions in trade shift this to regions with high savings (eg: China, Germany)[fn:: Written in 2013, this seems incredibly prescient about the Trump phenomenon].
  - Regions with surpluses are dependent on high-demand regions to siphon off the savings & excess production, otherwise their own supply and demand cannot balance, and all their hitherto productive investments will turn unproductive (unless they can raise their consumption drastically). This is the position China & Germany are in.
  - Nicely worked out example of Germany-Spain system. (Presumably could equally well have been Greece instead of Spain. Also, I wonder whether this explains the impetus for the Catalonian separatist movement)
  - Trade war is how regions negotiate/assign global unemployment; so expect trade tensions to be increasingly focal over the next several years.
- "Austerity economics" is completely wrong, because it presumes that universal thrift is a positive thing; in reality, you're always playing whack-a-mole to try and bury the excess savings in a zero-sum game. /The solution is not for low-savings countries to cut back on consumption, but for high-savings countries to increase consumption (lest they be forced into unemployment!)/
- At the global level, there are only three sustainable options:
  1. Increase in consumption by saving groups (Something China is trying to do[fn::Third Plenum reform proposals], and Germany has tepid steps towards)
  2. Direct savings into productive investment instead of producing inventory for export (and trying to export away savings)
     Private sector reluctance (hard to capture value), so likely government funded (eg: China research funding, CERN Higgs factory, Infrastructure projects towards productivity, etc.)
  3. High unemployment in savings heavy region.
  4. The above changes will likely be slow, so (as a stop gap) need countries with productive investment opportunities to keep demand high while the structural distortions are worked out.
- The first country to introduce downward wealth re-distribution will likely export away the employment and growth that result from a surge in consumption (effectively donating away the savings). Reduced global trade will likely provide impetus for local downward redistribution, but not until then.
- Increasing debt-fueled consumption in the US, or export-oriented investments in China are likely to worsen the underlying structural imbalances.
** In summary
#+begin_quote
/"It is utterly impossible, as this country has demonstrated again and again, for the rich to save as much as they have been trying to save, and save anything that is worth saving. They can save idle factories and useless railroad coaches; they can save empty office buildings and closed banks; they can save paper evidences of foreign loans; but as a class they cannot save anything that is worth saving, above and beyond the amount that is made profitable by the increase of consumer buying. It is for the interests of the well-to-do -- to protect them from the results of their own folly -- that we should take from them a sufficient amount of their surplus to enable consumers to consume and business to operate at a profit. This is not “soaking the rich”; it is saving the rich. Incidentally, it is the only way to assure them the serenity and security which they do not have at the present moment."/  (Marriner Eccles testimony to the US Congress, 1933)
#+end_quote
** My comments
- /FRB further injecting "liquidity" into capital markets is akin to pouring fuel on the fire, because it's all meant to go towards investment!/ Also, perversely, generating debt to fuel investment is effectively claiming that inequality is /"not high enough"/ to produce the necessary investment, for the given consumption level!
- Note: *The same likely applies even if the inequality is driven by technology/automation, and in fact explains the imperial dynamics of the industrial revolution quite well!*
- PS: Apart from inequality, population dynamics also contribute to the dynamics of savings. Young and old people weigh heavily on the consumption, while middle-aged people weigh heavily on savings... either for retirement, or to fuel consumption of the other two groups under their umbrella. An excess of savings-age population (unwilling to retire) will also likely cause complications.
- Unemployment in high-savings regions is reminiscent of the Maxwell construction for phase mixtures, stabilizing otherwise metastable states. (Employment being the order parameter; savings among employed must match consumption among unemployed)
- Alternate solution to "unemployment" -- instead of reducing the number of employed people, reduce the per-capita working hours.
- Basically, the rest of the world refuses to act as the "bank" for the thrifty, allowing them to run up large and sustained surpluses, because that is a hard promise to keep.
- The savings glut from US inequality combined with the savings glut from China has been a double whammy on the Rust Belt[fn::which is exactly where unemployment hit first! Only, the Republicans & progressive Democrats disagree on which of the two sources of savings glut to squeeze, while the moderate Democrats are stuck) (and rural US more broadly).
- Done well, healthcare welfare might be one form of wealth redistribution which is very difficult to export away to China (largely a service industry, and most value of drugs captured in the US). Likewise education, since American students don't go abroad for college. (/I don't mean loans, unless they're loans that are meant to be forgiven/). This would reduce (structural) inequality, by pipint (rich people) savings towards (poor people) consumption; any improvement in productive capacity from improved health or capabilities is a bonus.
- Applications to India? Sainath has mentioned that since the opening up of India's economy, India has had *massive* inequality growth. How does that affect unemployment, and trade deficits? Also, the propensity to buy gold contributes to the deficitr
- Applications to intra-US politics -- rural(central)-vs-urban(bicoastal)?
- Why do religions forbid lending with interest?
- We saw a use of this perspective to analyze the industrial revolution and imperialism. What about analyzing automation?

# * Rest of the book :noexport:
# ** Chapter 1: Trade imbalances
# *** Different explanations :noexport:
# Need to explain modern China, Germany, Japan, South Korea, etc.
# **** Infant industry (Alexander Hamilton 1791, US protectionism)
# Definitely can't explain contemporary Germany & Japan as technological infants, and supposedly China discourages too much internal competition (ideal for developing industry).
# **** Mercantilism
# - Policies to encourage export and discourage consumption; historically store surplus (as gold & silver) for sponsoring war effort.
# - But today, countries instead accumulate foreign exchange reserves i.e. currency and bonds. Pragmatically, useful not for military needs, but for maintaining sovereign currency stability, payments on foreign loans and obligations, and /guaranteeing access to imported commodities/ in pressing times.
# **** Underconsumptionist argument
# Most parsimonious explanation.
# *** Natural rebalancing consequences
# **** Currency values re-adjust such that exporter's currency appreciates and importer's depreciates, till we get a new equilibrium[fn::Presumably values correspond to chemical potentials given demand/supply]
# **** Alternately, direction of capital flows can be reversed
# *** Destabilizing effects of sustained imbalances
# **** Only policy/institutional/structural effects can cause sustained large-scale distortions; eg: sustained deficits without allowing increase in productive investments to (naturally) compensate. Adjustments inspite of constraints are more likely to be violent (aka financial crisis), eg: rapid deleveraging process.
# *** We have the tools
# **** Savings rate of any country are determined not so much by "thriftiness" of its citizens, but by the policies at home vis-a-vis trade partners.
# - Silly to (completely) attribute imbalances to the spendthrift Spaniards and the assiduous Germans, because national policies are typically far more powerful than individual orientations.
# - An effort by one country to change its trade balance must tautologically be compensated in the trade balances of its trading partners.
# - Likewise, any effort by one country to change its savings vis-a-vis investments will affect its current account, and hence ripple on to its trading partners.
# **** If we choose the wrong policy response, we'll exacerbate unemployment and trade conflict.
# - Exhorting/imposing austerity is likely to cause unemployment (and other distasteful ripple effects), because chasing thriftiness is ultimately a zero-sum game.
# *** Why so much confusion?
# **** The key factors are not just (directly) tariffs and currency manipulation, but indirectly affecting relation between consumption and GDP (along with a whole range host of other industrial, financial, and tax policies)
# **** Savings rate cannot easily be independently controlled with moralistic exhortations.
# **** Role of central bank, and the US dollar as global reserve currency.[fn::IMHO, it's a complicated mixed bag.]
# **** Far easier to make silly statements about culture eg: Confucian reversal in ~50 years.
# *** Some accounting identities (tautologically defined)
# 1. For every country, the current account (net income) and capital account (net balance sheet change) (difference) must balance to zero.
#    - Conservation of money; every dollar that enters a country must (eventually) leave the country, and be reflected the capital account meanwhile.
# 3. Current Account surplus = Domestic savings - Domestic investment
#    - Savings not invested locally must be invested abroad, automatically leading to a net excess of exports.
# 4. GDP = Consumption + Savings
#    - Everything a country produces must either be consumed (incl. wasted or discarded) or saved.

# ** Chapter Two: How does trade intervention work?
# *** Fredonia's import tariffs
# **** First-order effect: Import substitution, or elastic demand for imports means that imports reduce, reducing trade deficit.
# **** Second-order effect: If no substitutes, and inelastic demand, then consumption of other domestically produced items reduces. If the increased domestic savings (i.e. money raised from tariffs) are either invested abroad or locally displace FDI, this can reduce trade deficits.
# **** Question: Are the two effects equal in size (eg: could we prove that the sum is the same? If so, second order in dynamics, but not in size!) Or can we argue that the second order effect is systematically smaller in size?
# **** Better to think of the tariff as govt setting up the conditional -- either choose a local substitute, or give me the tariff so that I may reduce the deficit.

# ** Chapter Three: The many forms of trade intervention
# *** Anything that affects production & consumption is likely to affect savings and investment, and therefore affect trade balances. So, a whole host of domestic policies become effectively trade policies. (much like their implications for trade between different regions _within_ the country between whom trade is "free")
# *** Any policies that lead to transferms of resources from one sector of the economy to another are effectively (explicit or hidden) subsidies or tariffs; to the extent that they affect overall production and consumption, they have impact on trade imbalances.
# *** Effect of interest rates on household consumption might be reversed between US and China! (Key influencing factor might be people's feeling of wealthiness)
