#+TITLE: Thoughts on "A fine balance" by Rohinton Mistry
#+DATE: <2014-05-14 Wed>

The book needed some effort to get through the first third or so (took me a week!), while Mistry sets up his four characters and brings them together. After that, it's simply un-put-downable and I read the remaining two-thirds in one sitting. When I finished, it was 7am in the morning and I'd been reading all night!

#+begin_quote
/Life is a comedy to those who think and tragedy to those who feel./
#+end_quote


It's impossible not to feel overwhelmed by the absolutely heart-wrenching tale. I feel devastated and bitter. 1984 is the only other book which affected me like this. Wretched story but sublime writing... it feels effortless and poignant at the same time. I typically read to seek escape, but this is /so/ not the kind of book for that. I definitely wasn't prepared for this.

The book had some fine humour -- spontaneous and witty and made me really laugh. It shows how people in the direst situations are still capable of laughing genuinely. And smile and hope. And just when you think that the glimmer of hope will lead to sunrise, Mistry pulls out the rug from under your feet and leaves you with a cold and treacherous dawn followed by sunshine as normal, which seems particularly cruel since it does little to shine light on the protagonist's lives, almost as if it were a matter-of-fact occurrence and their suffering was nobody's concern.

The author has produced something so stunning that I feel thoroughly inadequate to judge it. The question that haunts me is: what do I get out of this book? What to make of it? It is such a awe-stricking experience that I can't just let it be and move on.

It feels like a tragedy without any moral or lesson to learn. Almost every character in the book is a good and sincere person (limited by a perspective based on their circumstances) but fickle fate wrings them through misery for no obvious reason -- to the extent that their fight almost seems futile. It conveys the hopelessness and powerlessness felt by the protagonists -- which denies you any possible sense of catharsis. Everything seems bleak, with no hope for redemption.

An author doesn't always need to have an upshot for a book. It could be an honest /description/ leaving the readers to make their own observations. But if I had to manufacture some meaning, I'd say that it gives me a hint of how incredibly privileged a life I lead, compared to a large number of people.
 
#+begin_quote
/"You fellows are amazing... Everything happens to you only. Each time you come here, you have a new adventure story to entertain us"/
#+end_quote


Because of all the challenges the protagonists faced, they come away with the most stories. They can at least feel good that they did not live out their drudgery silently but like the spider, they were constantly trying to climb out of the well even if they kept slipping and sliding on the slime. Their lives and struggles have a certain depth and dignity. Maybe that's the only honest measure of a life /"well-lived"/.

#+begin_quote
/"You see, you cannot draw lines and compartments, and refuse to budge beyond them. Sometimes you have to use your failures as stepping-stones to success. You have to maintain a fine balance between hope and despair."/
#+end_quote
