#+TITLE: On verifiability and automating knowledge work
#+AUTHOR: Siva Swaminathan
#+DATE: <2026-09-01 Tue>
#+FILETAGS: :substack:shorts:ai:
#+OPTIONS: toc:nil

I've been reading some chatter about how everything that can be verified can easily be automated, and how this covers much of knowledge work (along with exhortations of how this should push AI services towards outcome-based pricing rather than token-based). I want to rebut the strong version of that claim by pointing out a neglected bit of nuance.

To delegate something to be “solved”, you don't just need a verifier, but you need to be able to write it down /ex ante/ in a (smart) contract before you kick off the work. But most knowledge work is under-specified, and can't be carved into discrete units with fully defined outcomes; discovery and scoping are intrinsic to it.

This is what is underlying the common advice to get moving and avoid analysis paralysis. That's also why software gave up on waterfall and moved towards agile as software systems became more complex.

In essence, there is sometimes no way to specify the goal / verifier /a priori/ without first understanding how to solve the problem! This is related to the AI failure mode articulated in [[file:adaptive-conversational-tempo-for-ai-cognitive-companions.html][my previous post]], that it prematurely interprets your developing thoughts as fleshed-out task descriptions. I suspect AI gets trained towards this behavior because this is what is needed to “automate” work!
